<?php

namespace Drupal\sections;

use Caxy\HtmlDiff\HtmlDiffConfig;

class SectionsHtmlDiff extends \HtmlDiffAdvanced {

  /**
   * @param string              $oldText
   * @param string              $newText
   * @param HtmlDiffConfig|null $config
   *
   * @return self
   */
  public static function create($oldText, $newText, HtmlDiffConfig $config = null)
  {
    $diff = new self($oldText, $newText);

    if (null !== $config) {
      $config->setMatchThreshold(0);
      $diff->setConfig($config);
    }

    return $diff;
  }

  protected function diffList($oldText, $newText) {
    $diff = SectionsListDiffLines::create($oldText, $newText, $this->config);
    return $diff->build();
  }


  public function initPurifier($defaultPurifierSerializerCache = NULL) {

    if (null !== $this->purifierConfig) {
      $HTMLPurifierConfig  = $this->purifierConfig;
    } else {
      $HTMLPurifierConfig = \HTMLPurifier_Config::createDefault();
    }

    // Cache.SerializerPath defaults to Null and sets
    // the location to inside the vendor HTMLPurifier library
    // under the DefinitionCache/Serializer folder.
    if (!is_null($defaultPurifierSerializerCache)) {
      $HTMLPurifierConfig->set('Cache.SerializerPath', $defaultPurifierSerializerCache);
    }

    // Cache.SerializerPermissions defaults to 0744.
    // This setting allows the cache files to be deleted by any user, as they are typically
    // created by the web/php user (www-user, php-fpm, etc.)
    $HTMLPurifierConfig->set('Cache.SerializerPermissions', 0777);

    $def = $HTMLPurifierConfig->getHTMLDefinition(TRUE);
    $def->addElement(
      'section',
      'Block',
      'Flow',
      []
    );
    $def->addAttribute('section', 'class', 'CDATA');

    $this->purifier = new \HTMLPurifier($HTMLPurifierConfig);
  }

  public function build() {
    // 1. Equality
    if ($this->oldText == $this->newText) {
      $this->content = $this->newText;
      return $this->newText;
    }
    return parent::build(); // TODO: Change the autogenerated stub
  }


}
